@startuml
'https://plantuml.com/sequence-diagram

autonumber

Main -> Labyrinthe: genererMonstre()
activate Labyrinthe

Labyrinthe -> Monstre: Monstre()
activate Monstre
Labyrinthe <-- Monstre
deactivate Monstre

Labyrinthe -> Labyrinthe: positionAleatoire()
Labyrinthe <-- Labyrinthe: int[]




Labyrinthe -> Labyrinthe: ajouterMonstre(Monstre m, x, y)

Main <-- Labyrinthe
deactivate Labyrinthe




@enduml